### ISSUE TITLE
Example of JS code in addition to JSON configuration?

### ISSUE THREAD

**Issue by dahjelle** [hapijs/rejoice#12]
Hi!

I'm sure I'm missing something obvious, but it isn't clear to me how the JSON configuration file listed in the README hooks up with the JavaScript file I assume must exist somewhere defining routes, etc. Would it be possible to have a 'full-stack' example? Or am I entirely misunderstanding how rejoice is to be used?

**Comment by dahjelle** [comment]
You can ignore this—I think I'm trying to solve a different problem than `rejoice` does anyhow. Thanks!

**Comment by lloydbenson** [comment]
You may be looking more at glue (which is a library rejoice is based off
of).  This is just a simple cli utility which is based on glue to pass in a
configuration.  Typically this will get used in conjunction with confidence.
