### ISSUE TITLE
yaml support

### ISSUE THREAD

**Issue by boneskull** [hapijs/rejoice#24]
would you accept a PR for supporting a manifest file in YAML format?

**Comment by lloydbenson** [comment]
I don't think I want to natively support yaml.  However, you should be able to make a plugin that has rejoice has a dependent and just translates yml into the proper manifest.  Or you could clone this and translate it directly to glue (which is what this module does).  Then when you are all set and have a working plugin just submit it to hapijs.com/plugins and we can add it to the page.  If we get alot of requests for yaml in the future, I could reconsider this but I'd like it to be consistent through all hapi projects.  Thanks for asking!
