### ISSUE TITLE
Question: Typical Use Case

### ISSUE THREAD

**Issue by ambrons** [hapijs/rejoice#43]
I'm in the process of a PR to separate the behavior of `-p` and `-p` + `-r` into another command-line option.  

I'm seeking guidance on the typical use case:

1. `rejoice -c config.json -p ./lib`
   For the purpose of specifying the location of hapi plugins in the manifest

2. `rejoice -c config.json -r module -r module`
   No need for `-p` and use `./node_modules` as the location for `-r`

3. `rejoice -c config.json -r module -p path_to_base_dir_node_modules_used_by_dash_r`
  Coupling `-r` and `-p` together.

**Comment by lloydbenson** [comment]
what if you have both 1 and 2?

**Comment by lloydbenson** [comment]
1.  The use case for this originally was you may not always start this from the directory where it is installed.  So it would need to know where the node_modules was.  I am not positive that is still the case.

2.  seems reasonable

3.  Depends a bit on one, but id probably have another flag thats specific to the -r one and ensure -r exists if you use it.

Other than that what guidance are you looking for specifically?

**Comment by ambrons** [comment]
This looks good.  I'll do a follow up with the PR.
