### ISSUE TITLE
upgrade rejoice to new hapijs standards

### ISSUE THREAD

**Issue by lloydbenson** [hapijs/rejoice#46]
es 6, node 4.x, new hapi styles.  Note: awaiting a glue PR https://github.com/hapijs/glue/pull/42 to get glue upgraded at the same time.  Please do not merge until this has been done and I will include that.

**Comment by kevinmstephens** [comment]
is this ready to ship? would love to start using it.

**Comment by lloydbenson** [comment]
I am waiting for my PR to be reviewed.  Since it is the holidays this has been slow.  Glue just came out a day or 2 ago.  Feel free to use the PR commit until then.

**Comment by Marsup** [comment]
Quickly reviewed it, hopefully I didn't miss anything.

**Comment by kevinmstephens** [comment]
Thanks so much!

**Comment by lloydbenson** [comment]
3.x should be published.  Let me know if you run into any issues.
