### ISSUE TITLE
Dealing with node and local modules and the -p flag

### ISSUE THREAD

**Issue by millette** [hapijs/rejoice#57]
I am new to the hapi universe and giving rejoice a try, I encountered this error:
```
module.js:327
    throw err;
    ^
Error: Cannot find module 'vision'
[...]
```

when trying to launch it with
```
rejoice -c manifest.json
```
and a few variations with -p [DIRECTORY], always getting the same error.

I already had a manifest.json file, which I've attached. I'm also attaching the simple glue script I am using (before turning to rejoice) which works as expected.

vision and other required npm modules are all referenced in package.json and installed.

*Oh well, attaching files isn't working for me now, so here we go*:

manifest.json:
```
{
  "connections": [ { "port": 8800 } ],
  "registrations": [
    { "plugin": "vision" },
    {
      "plugin": {
        "register": "visionary",
        "options": {
          "engines": { "pug": "pug" },
          "path": "tpls"
        }
      }
    },
    {
      "plugin": { "register": "./routes/bap" },
      "options": { "routes": { "prefix": "/woot" } }
    },
    { "plugin": "./routes/home" },
    {
      "plugin": {
        "register": "good",
        "options": {
          "reporters": {
            "console": [
              {
                "module": "good-squeeze",
                "name": "Squeeze",
                "args": [{
                  "response": "*",
                  "log": "*"
                }]
              },
              { "module": "good-console" },
              "stdout"
            ]
          }
        }
      }
    }
  ]
}
```

server.js: (my current alternative to rejoice)
```
'use strict'

const Glue = require('glue')

Glue.compose(require('./manifest.json'), { relativeTo: __dirname })
  .then((server) => {
    server.start()
    return server
  })
  .then((server) => {
    console.log('hapi days!', server.info.uri)
  })
  .catch((err) => {
    console.error('ERROR:', err)
  })
```

**Comment by devinivy** [comment]
Just to be extra sure, the same directory in which you run `rejoice -c manifest.json` you can also `ls node_modules/vision`?

**Comment by millette** [comment]
Exactly, yes.

**Comment by devinivy** [comment]
Yes, so the only way I was able to get this to work was to install rejoice locally (within node_modules), or set the relative path to node_modules with `-p` and change my manifest to list each plugin relatively.

So,
`node_modules/.bin/rejoice -c manifest.json`
```
{"registrations":[{ "plugin": "vision" }]}
```

or

`rejoice -c manifest.json -p $(pwd)/node_modules`
```
{"registrations":[{ "plugin": "./vision" }]}
```

Curious what @lloydbenson thinks about it all!

**Comment by millette** [comment]
Confirming I was running rejoice globally. Thanks for having a look.

**Comment by lloydbenson** [comment]
Personally I think its better to not run rejoice globally (if you want to anyway you can run the -p as suggested).  If you just have it as a dependency in your package.json you can then have a start with just rejoice if you are looking at standard ways of doing things.  If you run it globally, you likely will forget about it and not keep it up to date and will run into issues in the future.

**Comment by devinivy** [comment]
I suppose you could also use global rejoice and set `NODE_PATHS` as described [here](https://nodejs.org/api/modules.html).  I do think a note about this stuff in the docs would be useful, esp since the examples show use of plugins that live in `node_modules`.

**Comment by millette** [comment]
I installed rejoice locally and added the following to my package.json:
```
"scripts": {
    "rejoice": "rejoice -c manifest.json -p $(pwd)"
}
```

Which is equivalent to running node_modules/.bin/rejoice when I type "npm run rejoice". I still needed to pass the -p flag to find ./routes/home and my other custom routes. It feels a bit redundant having to pass -p $(pwd), but at least I have both glue and rejoice working from the same manifest.json file.

**Comment by millette** [comment]
I'm closing the issue, feel free to reopen if needs be.
