### ISSUE TITLE
upgrade rejoice dependencies

### ISSUE THREAD

**Issue by lloydbenson** [hapijs/rejoice#64]
Looks like there is a new glue and other updates to dependencies.  This is always a breaking change as with glue, you don't need to include which hapi version you are using.

**Comment by dkolba** [comment]
@lloydbenson is this still maintained? I am currently in the planning phase for a new project and love rejoice. Thanks

**Comment by lloydbenson** [comment]
It is, I'll get a PR soon.

**Comment by dkolba** [comment]
👍
