### ISSUE TITLE
Deprecate?

### ISSUE THREAD

**Issue by hueniverse** [hapijs/rejoice#68]
Anyone using this module? Time to deprecate?

If not, please open a hapi v17 issue to migrate.

**Comment by lloydbenson** [comment]
I can migrate this, but I usually wait for its main dependency glue to migrate.  As far as I can tell glue is still waiting to be merged and published.  Once this is done I can start work on getting this ported.  I am still using it but if I am the only one I can easily migrate to something else.

**Comment by deedubs** [comment]
Glue@5 is on 17 now https://github.com/hapijs/glue/blob/v5.0.0/package.json#L21

**Comment by lloydbenson** [comment]
Thanks @deedubs the work starts!

**Comment by lloydbenson** [comment]
I am slowly working through catching up on all the changes.  I'd be happy to take a PR if someone is in a big hurry but wanted to update that I haven't forgotten about this.  As with many other users I am catching up on all the great changes.

**Comment by deedubs** [comment]
Exciting stuff! Is there a WIP we could collab on?

**Comment by dylancwood** [comment]
@lloydbenson @deedubs: I would also be interested in collaborating on this update. @lloydbenson, perhaps we can all send commits to a common fork of this until we are ready for the maintainers to review our work?

**Comment by lloydbenson** [comment]
Sorry for the slow response, the holidays was pretty hard on my time.  I am back to it.  I did make it a pretty good ways but ran into a few things and then struggled to find time again.  But regardless I am starting to do smaller commits now to lloydbenson/rejoice so feel free to take a look there and as always I am open to PRs.  I am just going through the package updates, errors, etc.  Lots of stuff has changed and I am reading through the doc and figuring things out.  When I hit a temp road block I'll mention it in case anyone knows.

**Comment by hueniverse** [comment]
4 months later...

**Comment by lloydbenson** [comment]
Ok, finally got some time to finish this up (new job helped alot).  @dylancwood or @deedubs can you test this out, make sure it works and then I can publish it?

**Comment by lloydbenson** [comment]
version 5 now published.
